### PR TITLE
change to the newer lightweight postinstall

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
changing to https://github.com/opencollective/opencollective-postinstall

### CODE REVIEW

**Review by xdamman — COMMENTED** [review]
lgtm
have you tested it?

**Comment by monkeywithacupcake** [comment]
I am not sure how to test it without messing up someone's repo. How can I test this @xdamman?

**Comment by monkeywithacupcake** [comment]
My patch does not work - when I try to use it like I used the setup branch,

`./dist/bin/opencollective.js setup -r erikras/redux-form -i`
`./dist/bin/opencollective.js light-postinstall-patch -r erikras/redux-form -i`

 I get:

`zsh: no such file or directory: ./dist/bin/opencollective.js`

**Comment by monkeywithacupcake** [comment]
Tested on Open Collective redux-form

**Comment by monkeywithacupcake** [comment]
Hi @xdamman  - I think that I may need to add opencollective-postinstall to this `return execSync` - I'm not super sure. I've been digging all over the code trying to figure out where it should be installed - since we add it to the package json ...or maybe I don't need it?
```
if (fs.existsSync(path.join(projectPath, "package.json"))) {
        pkg = getPackageJSON(projectPath);
        if (!pkg.dependencies || !pkg.dependencies.opencollective) {
          console.log("Running npm install --save opencollective");
          return execSync(`npm install --save opencollective >> ${logsFile} 2>&1`, { cwd: projectPath });
        }
      }
    });
```

**Comment by xdamman** [comment]
Can you point to the right place in the script?
I couldn't find this snippet in the code in this repo.

**Comment by monkeywithacupcake** [comment]
line 130 of setup.js in setup branch: https://github.com/opencollective/opencollective-cli/blob/setup/src/commands/setup.js

**Comment by xdamman** [comment]
ah yes, seems indeed like this should be `opencollective-postinstall`.

**Comment by monkeywithacupcake** [comment]
Ok. I changed that and I'll be moving forward with these again. THANK YOU.

**Pull request merged**
